import Menu from './component/menu'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'simple-blog-website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full h-screen bg-gradient-to-r from-cyan-300 to-blue-400'>
          <Menu />
          {children}
        </div>
      </body>
    </html>
  )
}
